# https://github.com/hadolint/hadolint
ignored:
  - DL3013 # warning: Pin versions in pip installs.
  - DL3033 # warning: Specify version with `yum install -y <package>-<version>`.
  - DL3042 # warning: Avoid use of cache directory with pip. Use `pip install --no-cache-dir <package>`
