name: 'docker build ubuntu2404 sglang'

on:


  push:
    paths:
      - 'docker/Dockerfile-ubuntu2404-sglang'
      - 'extend/customize_sglang.sh'
      - 'extend/start_sglang.sh'
      - 'build_docker_ubuntu2404_sglang.yaml'
      - '.hadolint.yaml'

jobs:

  build_docker_ubuntu2404_sglang:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      DOCKER_FILE: 'docker/Dockerfile-ubuntu2404-sglang'
      IMG_TAGS: 'didierdurand/lic-sglang:ubuntu2404-0.4.9.post2,didierdurand/lic-sglang:ubuntu2404-latest'

    steps:

      - name: 'free disk space'
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 'gain some disk space for build of large images'
        run: |
          # see https://github.com/apache/flink/blob/02d30ace69dc18555a5085eccf70ee884e73a16e/tools/azure-pipelines/free_disk_space.sh
          echo "Freeing up disk space on CI system"
          echo "Listing 100 largest packages"
          dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
          df -h
          echo "Removing large packages"
          sudo apt-get remove -y '^dotnet-.*'
          sudo apt-get remove -y '^llvm-.*'
          sudo apt-get remove -y '^libllvm.*'
          sudo apt-get remove -y '^temurin-.*'
          sudo apt-get remove -y 'php.*'
          # sudo apt-get remove -y google-cloud-sdk google-cloud-cli-anthoscli 
          sudo apt-get remove -y azure-cli microsoft-edge-stable google-chrome-stable firefox powershell mono-devel
          sudo apt-get autoremove -y
          sudo apt-get clean
          df -h
          echo "Removing large directories"
          rm -rf /usr/share/dotnet/
          df -h

      - name: 'checkout git code'
        uses: actions/checkout@v4

      - name: 'log in to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 'lint docker file'
        # see https://github.com/hadolint/hadolint
        run: |
          # https://github.com/hadolint/hadolint
          docker run --rm -i -v ${PWD}/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < ${{env.DOCKER_FILE}}

      - name: 'set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'build on prod repo and push it to Docker Hub'
        if: github.repository == 'didier-durand/llms-in-clouds'
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ${{env.DOCKER_FILE}}
          tags: ${{env.IMG_TAGS}}

      - name: 'build image of dev repo with no push to Docker Hub'
        if: github.repository != 'didier-durand/llms-in-clouds'
        uses: docker/build-push-action@v6
        with:
          push: false
          file: ${{env.DOCKER_FILE}}
          tags: ${{env.IMG_TAGS}}
